### ISSUE TITLE
Hey i guess you have force pushed to the repository, Old commit files are not found

### ISSUE THREAD

**Issue by vijishmadhavan** [tadangkhoa1999/HairstyleGAN#3]
Amazing work!!

The results are not good and does not look similar to the output. I guess this the issue
I have updated from using [stylegan](https://github.com/NVlabs/stylegan) to using [stylegan2-ada-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch). But I have not updated the stylegan-encoder yet. You can use older commit for better result.

Can you help?

**Comment by HieuVT611** [comment]
![image](https://github.com/tadangkhoa1999/HairstyleGAN/assets/171055348/9e782179-e05b-4552-adaa-bb9722e7d284)
Hi, I have this problem, did you fix it before? can you help me brother, where is the seed0056 ?

**Comment by tadangkhoa1999** [comment]
I no longer have information about this source code, however the random seed files are only for testing, you can ignore them if you can't find the files.
